url: "https://polyagonal1.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/DofE-website" # the subpath of your site, e.g. /blog
title: "Alex's Amazing Origami" # the name of your site, e.g. ACME Corp.

lang: "en-GB"

exclude:
  - _sass/
  - assets/css/main.scss
  - bin/

include:
  - assets/css/main.css